### ISSUE TITLE
issue with mqtt client

### ISSUE THREAD

**Issue by devzwf** [snicker/juicepassproxy#21]
getting 

Traceback (most recent call last):
  File "/juicepassproxy/juicepassproxy.py", line 309, in <module>
    main()
  File "/juicepassproxy/juicepassproxy.py", line 296, in main
    handler = JuiceboxMessageHandler(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/juicepassproxy/juicepassproxy.py", line 46, in __init__
    self._init_devices()
  File "/juicepassproxy/juicepassproxy.py", line 66, in _init_devices
    self._init_device_energy_lifetime(device_info)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JuiceboxMessageHandler' object has no attribute '_init_device_energy_lifetime'. Did you mean: '_init_device_power_lifetime'?
2023-11-14 00:07:54,373 DEBUG      Shutting down MQTT client
2023-11-14 00:07:54,374 DEBUG      Shutting down MQTT client
2023-11-14 00:07:54,374 DEBUG      Shutting down MQTT client
--------------------------------

since today ...

Using edge image.... just as FYI

**Comment by snicker** [comment]
sorry about that - likely from a merge just a few hours ago- fixed now @devzwf and edge should rebuild shortly

**Comment by devzwf** [comment]
no worries 
we are there for testing :)
