### ISSUE TITLE
Error in JuiceboxUDPCUpdater: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Snuffy2** [snicker/juicepassproxy#26]
Running the version in #23. Not sure this actually needs to be fixed as it seemed to recover and retry again but this was in the logs:
```
juicepassproxy  | 2023-11-14 22:04:41,617 DEBUG      JuiceboxUDPCUpdater check...
juicepassproxy  | 2023-11-14 22:04:41,725 ERROR      Error in JuiceboxUDPCUpdater: [Errno 104] Connection reset by peer
juicepassproxy  | Traceback (most recent call last):
juicepassproxy  |   File "/juicepassproxy/juicepassproxy.py", line 253, in start
juicepassproxy  |     with JuiceboxTelnet(self.juicebox_host, 2000) as tn:
juicepassproxy  |   File "/juicepassproxy/juicebox_telnet.py", line 11, in __enter__
juicepassproxy  |     self.connection = self.open()
juicepassproxy  |                       ^^^^^^^^^^^
juicepassproxy  |   File "/juicepassproxy/juicebox_telnet.py", line 22, in open
juicepassproxy  |     self.connection.read_until(b">")
juicepassproxy  |   File "/usr/local/lib/python3.12/telnetlib.py", line 320, in read_until
juicepassproxy  |     self.fill_rawq()
juicepassproxy  |   File "/usr/local/lib/python3.12/telnetlib.py", line 528, in fill_rawq
juicepassproxy  |     buf = self.sock.recv(50)
juicepassproxy  |           ^^^^^^^^^^^^^^^^^^
juicepassproxy  | ConnectionResetError: [Errno 104] Connection reset by peer
juicepassproxy  | 2023-11-14 22:04:41,958 DEBUG      remote: b'CMD22204A0040M040C124S185!AWT$'
juicepassproxy  | 2023-11-14 22:05:11,729 DEBUG      JuiceboxUDPCUpdater check...
juicepassproxy  | 2023-11-14 22:05:12,080 DEBUG      UDPC IP incorrect, updating...
juicepassproxy  | 2023-11-14 22:05:12,808 DEBUG      UDPC IP Saved
```

**Comment by snicker** [comment]
we can probably catch this particular exception and retry after only 3s instead of 30s. This is probably to be expected- I think the device pretty regularly kicks the telnet connection at random. it would happen quite a bit while I was testing without any recognizable pattern or interval.

also of note is that the telnet server only accepts one connection simultaneously.
